// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXTL0Cf8ji_baZdmsQtPnuYpoLynJ14nc',
    appId: '1:590880518197:web:110ee8f626ac68d92a017c',
    messagingSenderId: '590880518197',
    projectId: 'quizletschool-56675',
    authDomain: 'quizletschool-56675.firebaseapp.com',
    storageBucket: 'quizletschool-56675.appspot.com',
    measurementId: 'G-JJ7ER407RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW21NOBca2toifclDorA35eTIhCYuFvZ0',
    appId: '1:590880518197:android:541d724430197ccd2a017c',
    messagingSenderId: '590880518197',
    projectId: 'quizletschool-56675',
    storageBucket: 'quizletschool-56675.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOwnWdx0XYF4gvrPvAc4pti1i5KDcYqrU',
    appId: '1:590880518197:ios:284ed78f7ed228772a017c',
    messagingSenderId: '590880518197',
    projectId: 'quizletschool-56675',
    storageBucket: 'quizletschool-56675.appspot.com',
    iosBundleId: 'com.example.flutterck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOwnWdx0XYF4gvrPvAc4pti1i5KDcYqrU',
    appId: '1:590880518197:ios:284ed78f7ed228772a017c',
    messagingSenderId: '590880518197',
    projectId: 'quizletschool-56675',
    storageBucket: 'quizletschool-56675.appspot.com',
    iosBundleId: 'com.example.flutterck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXTL0Cf8ji_baZdmsQtPnuYpoLynJ14nc',
    appId: '1:590880518197:web:b106efb3b0dda4df2a017c',
    messagingSenderId: '590880518197',
    projectId: 'quizletschool-56675',
    authDomain: 'quizletschool-56675.firebaseapp.com',
    storageBucket: 'quizletschool-56675.appspot.com',
    measurementId: 'G-05BMXYE997',
  );

}